services:
  api:
    container_name: ludu-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nest
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
  nginx:
    container_name: ludu-nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx.conf:/nginx.conf
    depends_on:
      - api
    ports:
      - 8080:80
    links:
     - api:api
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - API_PORT=${API_PORT}
      - NGINX_MAX_BODY=${NGINX_MAX_BODY}
    command: /bin/sh -c "envsubst < ./nginx.conf > /etc/nginx/default.conf && nginx -g 'daemon off;'"
