---
# tasks file for luduBackend
- name: check if the folder Backend ludu is created
  ansible.builtin.file:
    path: /opt/luduBackend
    owner: user
    group: user
    mode: '0755'
    state: directory


- name: copy luduBackend server into /opt/luduBackend
  copy:
   src: ../../../server
   dest: /opt/luduBackend
   

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /opt/luduBackend/server
    files:
    - docker-compose.yml
