---
# tasks file for luduBackend
- name: check if the folder Backend ludu is created
  ansible.builtin.file:
    path: /opt/luduBackend
    owner: ludu
    group: ludu
    mode: '0755'
    state: directory

# - name: copy luduBackend server into /opt/luduBackend
#   copy:
#    src: luduBackend/files/server.tgz
#    dest: /opt/luduBackend
#    directory_mode:
#       tags:
#         - parentdir
        
- name: Extract luduBackend
  ansible.builtin.unarchive:
    src: luduBackend/files/server.tgz
    dest: /opt/luduBackend
    

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /opt/luduBackend/server
    files:
    - docker-compose.yml
