---
# tasks file for luduBackend
- name: create folder Backend ludu
  ansible.builtin.file:
    path: /opt/luduBackend
    owner: debian
    group: debian
    mode: '0755'
    state: directory


- name: copy luduBackend server into /opt/luduBackend
  copy:
   src: ../files/server
   dest: /opt/luduBackend
   state: present 

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /opt/luduBackend/server
    files:
    - docker-compose.yml
