export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';
export const RESET_STATUS_FILTER = 'RESET_STATUS_FILTER';
export const ACTIVATE_STATUS_FILTER = 'RESET_STATUS_FILTER';
export const DEACTIVATE_STATUS_FILTER = 'RESET_STATUS_FILTER';
