export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const RESET_CATEGORY_FILTER = 'RESET_CATEGORY_FILTER';
export const ACTIVATE_CATEGORY_FILTER = 'ACTIVATE_CATEGORY_FILTER';
export const DEACTIVATE_CATEGORY_FILTER = 'RESET_CATEGORY_FILTER';
