name: CI

on:
  push:
    paths:
    - 'server/**'
  pull_request:
    paths: 
    - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
      - name: Unit test for server
        uses: actions/setup-node@v2
        with:
          node-version: 19.1
      - run: cd ./
      - run: npm ci
      - run: npm run test