name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v3
      - name: Unit Test for server
        uses: actions/setup-node@v3
        with:
          node-version: 19.1
      - run: cd ./server 
      - run: npm ci
      - run: npm run test